[project]
name = "pypm"
version = "0.0.6"
description = ""
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aiomysql",
    "importlib_metadata",
    "pymongo",
    "redis",
    "requests",
    "rich",
]

[dependency-groups.dev]
dependencies = [
]